parameters:
    services.user_class: Istudyante\UserBundle\Services\UserService
    services.admin_user_class: Istudyante\UserBundle\Services\AdminUserService
    services.twig_user_class: Istudyante\UserBundle\Services\TwigUserService

    services.user_provider_class: Istudyante\UserBundle\Services\ChromediaAccountsUserProvider
    services.admin_user_provider_class: Istudyante\UserBundle\Services\AdminUserProvider
    
services:
    services.user:
        class: %services.user_class%
        abstract: true
        arguments: [@service_container]
        calls:
            - [setEventDispatcher, [@event_dispatcher]]
            #- [setEventFactory, [@events.factory]]
            - [setDoctrine, [@doctrine]]
            #- [setChromediaRequest, [@services.chromedia_request]]
            #- [setChromediaAccountsUri, [%chromedia_accounts_uri%]]
            - [setDoctrine, [@doctrine]]
            - [setSession, [@session]]
            #- [setSecurityContext, [@security.context]]

    services.admin_user:
        class: %services.admin_user_class%
        parent: services.user

    services.twig_user:
        class: %services.twig_user_class%
        parent: services.user

    services.user.twig.extension:
        class: Istudyante\UserBundle\Twig\UserTwigExtension
        public: false
        calls:
            - [setUserService, [@services.twig_user]]
        tags:
            - { name: twig.extension }

    services.user_provider:
        class: %services.user_provider_class%
        abstract: true
        arguments: [@service_container]

    services.admin_user_provider:
        class: %services.admin_user_provider_class%
        parent: services.user_provider
        calls:
            - [setUserService, [@services.admin_user]]