<<<<<<< HEAD
admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

DemoBundle:
    resource: "@DemoBundle/Resources/config/routing.yml"
    prefix: /
=======
AdminBundle:
	resource: "@AdminBundle/Resources/config/routing.yml"
	prefix: /
>>>>>>> b9a8876f7e0128c0f81ce04dfeadc0bfdd01ebab
