jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    acl:
        connection: default
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Istudyante\UserBundle\Entity\AdminUser:
            algorithm: sha256
            iterations: 1
            encode_as_base64: false
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    developer: { password: 123456, roles: 'ROLE_DEVELOPER' }
                    test: { password:123456, roles: 'ROLE_ADMIN' }
                    
        admin_user_provider:
            id: services.admin_user_provider
        
    firewalls:
        main:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        utilities_secured_area:
            pattern: ^/secured-utilities
            access_denied_url: /helper/access-denied
            http_basic:
                realm: "Secured Developers Area"

        admin_user.login:
            pattern: ^/admin/login$
            security: false

        admin_secured_area:
            pattern: ^/admin
            access_denied_url: /admin/access-denied
            form_login:
                login_path: /admin/login
                check_path: /admin/login-check
                always_use_default_target_path: false
                default_target_path: /admin/dashboard
                remember_me: false
                failure_path: /admin/login

            logout:
                path:   /admin/logout
                target: /admin/login
            
    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: [ ROLE_ADMIN, IS_AUTHENTICATED_REMEMBERED, IS_AUTHENTICATED_FULLY ]}
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
