<?php

namespace Istudyante\AdminBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AdminUserController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Istudyante\AdminBundle\Controller\AdminUserController();
        return $instance;
    }
}
