Istudyante\UserBundle\Entity\AdminUserType:
    type: entity
    table: admin_user_types
    repositoryClass: Istudyante\UserBundle\Repository\AdminUserTypeRepository
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 250
            fixed: false
            nullable: false
        status:
            type: integer
            nullable: false
    manyToMany:
        adminUserRoles:
            targetEntity: Istudyante\UserBundle\Entity\AdminUserRole
            cascade: {  }
            mappedBy: null
            inversedBy: adminUserTypes
            joinTable:
                name: admin_user_type_roles
                joinColumns:
                    -
                        name: admin_user_type_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: admin_user_role_id
                        referencedColumnName: id
            orderBy: null
    oneToMany:
        adminUsers:
            targetEntity: Istudyante\UserBundle\Entity\AdminUser
            mappedBy: adminUser
    lifecycleCallbacks: {  }
