Istudyante\UserBundle\Entity\AdminUser:
    type: entity
    table: admin_users
    repositoryClass: Istudyante\UserBundle\Repository\AdminUserRepository
    fields:
        accountId:
            id: true
            type: bigint
            nullable: false
            column: account_id
            generator:
                strategy: NONE
        status:
            type: boolean
            nullable: false
    manyToOne:
        adminUserType:
            targetEntity: Istudyante\UserBundle\Entity\AdminUserType
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                admin_user_type_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
