admin_login:
    pattern: /admin/login
    defaults: { _controller: AdminBundle:Default:login }
    requirements:
        _method:  GET|POST

admin_login_check:
    pattern:   /admin/login-check
    
admin_logout:
    pattern:  /admin/logout
