parameters:
    services.admin_user_provider_class: Istudyante\AdminBundle\Services\AdminUserProvider
    services.user_provider_class: Istudyante\AdminBundle\Services\AccountsUserProvider
    
services:
    services.admin_user_provider:
        class: %services.admin_user_provider_class%
        arguments: [@doctrine]
        
    services.user_provider:
        class: %services.user_provider_class%
        abstract: true
        arguments: [@service_container,@doctrine]
